#!/bin/bash

# Configuration.
LOG_PATH="qsub_logs"

# Make the logging directory if it does not exist yet.
mkdir -p $LOG_PATH

# Extract the SGE_RREQ variable if present.
CMD=$2
if $(echo $2 | grep "^SGE_RREQ="  > /dev/null); then
  SGE_RREQ=$(echo $2 | sed 's/^[^"]*"\([^"]*\)" .*/\1/')
  CMD=$(echo $2 | sed 's/^[^"]*"[^"]*" //')
fi

# Choose an output file.
OUTPUT=".$(date +%s)_$RANDOM"

# Deploy the job.
cat << EOF | qsub -sync y -cwd -o $LOG_PATH -e $LOG_PATH $SGE_RREQ -- - 1>&2
#!/bin/sh
echo Start: \`date\`
echo Name: \$JOB_NAME
echo ID: \$JOB_ID
echo Queue: \$QUEUE
echo Host: \$HOSTNAME
echo User: \$LOGNAME
echo SGE_RREQ: \""$SGE_RREQ"\"
echo Command:
echo ---
echo "$CMD"
echo ---
echo Output:
echo ---
$CMD > $OUTPUT
echo 
echo ---
echo End: \`date\`
EOF

# Return the output (if any) and clean up.
cat $OUTPUT
rm $OUTPUT
